### model
model_name_or_path: /mnt/raid0hdd1/liang/models/Llama-3.2-1B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all

### dataset
dataset: EG_entailment_train
dataset_dir: /home/liang/FrequenctBias/finetune/data
template: llama3
cutoff_len: 512
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 4

### output
output_dir: /home/liang/FrequenctBias/finetune/saves/llama3.2-1b-lora-EG
logging_steps: 50
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard]

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.05
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 500
